/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package models;


import com.sun.istack.internal.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import sun.util.logging.PlatformLogger;

/**
 *
 * @author JC
 */
public class BloodPack extends javax.swing.JFrame {

    /**
     * Creates new form category
     */
    public BloodPack() {
        initComponents();
        table_update();
        PackType();
        BloodType();
    }
    
    String lname;
    String isAdmin;
    String userID;
    
     public BloodPack(String name, String isAdmin) {
        initComponents();
        this.lname = name;
        this.isAdmin = isAdmin;  
        table_update();
        PackType();
        BloodType();
    }

    Connection conl;
    PreparedStatement pst;
    ResultSet rs;
    String Driver = "com.mysql.jdbc.Driver";
    String jdbcLink = "jdbc:mysql://localhost/bloodbank";
    String jdbcUser = "root";
    String jdbcPass = "";
    
    public void getId(){
        try {
            Class.forName(Driver);
            conl = DriverManager.getConnection(jdbcLink, jdbcUser, jdbcPass);
            pst = conl.prepareStatement("select id from accounts where name=?");
            pst.setString(1, lname);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                userID = rs.getString("id");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PackType.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(PackType.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void edithistory(String action){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime now = LocalDateTime.now();
        String date = dtf.format(now);
        try {
            Class.forName(Driver);
            conl = DriverManager.getConnection(jdbcLink, jdbcUser, jdbcPass);
            pst = conl.prepareStatement("insert into edithistory (action,account,date)values(?,?,?) ");
            pst.setString(1, action);
            pst.setString(2, lname);
            pst.setString(3, date);
            pst.executeUpdate();      
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(PackType.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(PackType.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    public class PackTypeItem{
        int id;
        String name;
        
        public PackTypeItem(int id, String name){
            this.id = id;
            this.name = name;
        }
        
        public String toString(){
            return name;
        }
    }
    
     public class BloodTypeItem{
        int id;
        String name;
        
        public BloodTypeItem(int id, String name){
            this.id = id;
            this.name = name;
        }
        
        public String toString(){
            return name;
        }
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtstatus = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtbag = new javax.swing.JComboBox();
        txtblood = new javax.swing.JComboBox();
        txtdonor = new javax.swing.JTextField();
        txtdatecollected = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bag Type");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Exit");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Blood Type");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Blood Pack");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edit History");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Admin");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Blood Pack");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel8.setText("Blood Bank Management System");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Blood Pack", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setText("Status");

        txtstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "DeActive" }));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel12.setText("Blood Bag Type");

        jLabel13.setText("Blood Type");

        jLabel15.setText("Donor Name");

        jLabel16.setText("Date Collected");

        txtblood.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        jLabel18.setText("Quantity");

        jLabel19.setForeground(java.awt.Color.red);
        jLabel19.setText("Format: YYYY/MM/DD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtbag, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtblood, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdonor, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(txtdatecollected)
                            .addComponent(txtqty))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtdonor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtbag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtblood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(txtdatecollected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel18)
                        .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Blood Bag Type", "Blood Type", "Date Collected", "Donor Name", "Date Registered", "Registered By", "Quantity", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel8)))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void PackType(){
        try {
            Class.forName(Driver);
            conl = DriverManager.getConnection(jdbcLink, jdbcUser, jdbcPass);
            pst = conl.prepareStatement("select * from bagtype");
            ResultSet rs = pst.executeQuery();
            txtbag.removeAllItems();
            
            while(rs.next()){
                txtbag.addItem(new PackTypeItem(rs.getInt(1), rs.getString(2)));
            }
            
            
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public void BloodType(){
        try {
            Class.forName(Driver);
            conl = DriverManager.getConnection(jdbcLink, jdbcUser, jdbcPass);
            pst = conl.prepareStatement("select * from bloodtype");
            ResultSet rs = pst.executeQuery();
            txtblood.removeAllItems();
            
            while(rs.next()){
                txtblood.addItem(new BloodTypeItem(rs.getInt(1), rs.getString(2)));
            }
            
            
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    private void table_update(){
        try {
            int c;
            try {
                Class.forName(Driver);
                conl = DriverManager.getConnection(jdbcLink, jdbcUser, jdbcPass);
                pst = conl.prepareStatement("select bp.id,bp.bagtype_id,bp.bloodtype_id,bp.date_collected,bp.donor_name,bp.date_registered,bp.username,bp.qty,bp.status,pt.bagtype,bt.bloodtype from bloodpack bp,bagtype pt,bloodtype bt where bp.bagtype_id = pt.id and bp.bloodtype_id = bt.id");
                ResultSet rs = pst.executeQuery();
                
                ResultSetMetaData rsd = rs.getMetaData();
                c = rsd.getColumnCount();
                
                DefaultTableModel d = (DefaultTableModel)jTable1.getModel();
                d.setRowCount(0);
                
                
                while(rs.next()){
                    Vector v2 = new Vector();
                    
                    for(int i=1; i<=c; i++){
                       v2.add(rs.getString("id"));
                       v2.add(rs.getString("bagtype"));
                       v2.add(rs.getString("bloodtype"));
                       v2.add(rs.getString("date_collected"));
                       v2.add(rs.getString("donor_name"));
                       v2.add(rs.getString("date_registered"));
                       v2.add(rs.getString("username"));
                       v2.add(rs.getString("qty"));
                       v2.add(rs.getString("status"));
                    }
                    
                    d.addRow(v2);
                }               
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
         DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
         int selectIndex = jTable1.getSelectedRow();
        
         txtbag.setSelectedItem(d1.getValueAt(selectIndex, 1).toString());
         txtblood.setSelectedItem(d1.getValueAt(selectIndex, 2).toString()); 
         txtdatecollected.setText(d1.getValueAt(selectIndex, 3).toString());
         txtdonor.setText(d1.getValueAt(selectIndex, 4).toString());
         txtdatecollected.setText(d1.getValueAt(selectIndex, 5).toString());
         txtqty.setText(d1.getValueAt(selectIndex, 7).toString());
         txtstatus.setSelectedItem(d1.getValueAt(selectIndex, 8).toString());   
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.hide();
        new PackType(lname,isAdmin).setVisible(true);
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.hide();
        new BloodType(lname,isAdmin).setVisible(true);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1. getSelectedRow();

        int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());

        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to Delete the Record?", "Warning",JOptionPane.YES_NO_OPTION);

        if(dialogResult == JOptionPane.YES_OPTION){

            try {
                Class.forName(Driver);
                conl = DriverManager.getConnection(jdbcLink, jdbcUser, jdbcPass);
                pst = conl.prepareStatement("delete from bloodpack where id = ?");
                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Product Deleted");
                table_update();
                txtdonor.setText("");
                txtdatecollected.setText("");             
                txtdonor.setText("");   
                txtqty.setText("");        
                txtdonor.requestFocus();
                edithistory("Deleted Blood Pack ID: " + id);

            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1. getSelectedRow();

        int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());
        String donor = txtdonor.getText();
        String datec = txtdatecollected.getText();
        PackTypeItem pitem = (PackTypeItem)txtbag.getSelectedItem();
        BloodTypeItem bitem = (BloodTypeItem)txtblood.getSelectedItem();
        String qty = txtqty.getText();
        String status = txtstatus.getSelectedItem().toString();

        try {
            Class.forName(Driver);
            conl = DriverManager.getConnection(jdbcLink, jdbcUser, jdbcPass);
            pst = conl.prepareStatement("update bloodpack set donor_name=?,date_collected=?,bagtype_id=?,bloodtype_id=?,qty=?,status=? where id=?");
            pst.setString(1, donor);
            pst.setString(2, datec);
            pst.setInt(3, pitem.id);
            pst.setInt(4, bitem.id);
            pst.setString(5, qty);
            pst.setString(6, status);
            pst.setInt(7, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Blood Pack Updated");
            table_update();
            txtdonor.setText("");
            txtdatecollected.setText("");               
            txtqty.setText("");   
            txtdonor.requestFocus();
            edithistory("Edited Blood Pack ID: "+id);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String donor = txtdonor.getText();
        String datec = txtdatecollected.getText();
        PackTypeItem pitem = (PackTypeItem)txtbag.getSelectedItem();
        BloodTypeItem bitem = (BloodTypeItem)txtblood.getSelectedItem();
        String qty = txtqty.getText();
        String status = txtstatus.getSelectedItem().toString();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime now = LocalDateTime.now();
        String dater = dtf.format(now);
        int generatedID = 0;
        String query1 = "insert into bloodpack(bagtype_id,bloodtype_id,date_collected,donor_name,date_registered,username,qty,status)values(?,?,?,?,?,?,?,?)";
        try {
            Class.forName(Driver);
            conl = DriverManager.getConnection(jdbcLink, jdbcUser, jdbcPass);
            pst = conl.prepareStatement(query1,Statement.RETURN_GENERATED_KEYS);
            pst.setInt(1, pitem.id);
            pst.setInt(2, bitem.id);
            pst.setString(3, datec);
            pst.setString(4, donor);
            pst.setString(5, dater);
            pst.setString(6, lname);
            pst.setString(7, qty);
            pst.setString(8, status);
            pst.executeUpdate();
            ResultSet generatedKeyResult = pst.getGeneratedKeys();
            if(generatedKeyResult.next()){
                generatedID = generatedKeyResult.getInt(1);
            }
            JOptionPane.showMessageDialog(this, "Blood Pack ID: " + generatedID +" Added");
            table_update();
            txtdonor.setText("");
            txtdatecollected.setText("");  
            txtqty.setText(""); 
            txtdonor.requestFocus();
            edithistory("Blood Pack ID: " + generatedID +" Added");

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.hide();
        new EditHistory(lname,isAdmin).setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
       if(isAdmin.equals("Yes")){
            Accounts c = new Accounts();
            this.hide();
            c.setVisible(true);
       }  else {
           JOptionPane.showMessageDialog(this, "Only Admin accounts can use this feature");
           int dialogResult = JOptionPane.showConfirmDialog(null, "Do you log in an Admin account?", "Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                login l = new  login();
                this.hide();
                l.setVisible(true);
            }
       }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanel1MouseClicked

    
//    public String searchBagType(int id){
//        String name = "";
//        try {
//            Class.forName(Driver);
//            conl = DriverManager.getConnection(jdbcLink, jdbcUser, jdbcPass);
//            pst = conl.prepareStatement("select bagtype from bagtype where id=?");
//            pst.setInt(1, id);
//            rs = pst.executeQuery();
//            while(rs.next()){
//                name = rs.getString("bagtype");
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        return name;
//    }
//    
//     public String searchBloodType(int id){
//        String name = "";
//        try {
//            Class.forName(Driver);
//            conl = DriverManager.getConnection(jdbcLink, jdbcUser, jdbcPass);
//            pst = conl.prepareStatement("select bloodtype from bloodtype where id=?");
//            pst.setInt(1, id);
//            rs = pst.executeQuery();
//            while(rs.next()){
//                name = rs.getString("bloodtype");
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        return name;
//    }
    
//    public void search(){
//        int id = Integer.parseInt(txtsearch.getText());
//        String status ="";
//        String qty ="";
//        String bagtypeID = "";
//        String bloodtypeID = "";
//        String donorName = "";
//        String dateC = "";  
//        JOptionPane.showMessageDialog(this, "Id is "+id);
//                
//        try {
//            Class.forName(Driver);
//            conl = DriverManager.getConnection(jdbcLink, jdbcUser, jdbcPass);
//            pst = conl.prepareStatement("select bp.id,bp.bagtype_id,bp.bloodtype_id,bp.date_collected,bp.donor_name,bp.date_registered,bp.username,bp.qty,bp.status,pt.bagtype,bt.bloodtype from bloodpack bp,bagtype pt,bloodtype bt where bp.bagtype_id = pt.id and bp.bloodtype_id = bt.id and bp.id =?");
//            pst.setInt(1, id);
//            rs = pst.executeQuery();    
//            if(rs.next() == false){
//                JOptionPane.showMessageDialog(this, "Blood Pack not found Try Again");
//            } else {
//                while(rs.next()){
//                    bagtypeID = rs.getString("bagtype");
//                    bloodtypeID = rs.getString("bloodtype");
//                    donorName = rs.getString("donor_name");
//                    dateC = rs.getString("date_collected");  
//                    qty = rs.getString("qty");
//                    status = rs.getString("status");
//                }
//                JOptionPane.showMessageDialog(this, bagtypeID + " " + bloodtypeID + " " + donorName + " " + dateC + " " + qty + " " + status);
//                txtbag.setSelectedItem(bagtypeID);
//                txtblood.setSelectedItem(bloodtypeID);
//                txtdatecollected.setText(dateC);
//                txtdonor.setText(donorName);
//                txtqty.setText(qty);
//                txtstatus.setSelectedItem(status);
//                
//            }       
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
//        }
//         
//    }
    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BloodPack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox txtbag;
    private javax.swing.JComboBox txtblood;
    private javax.swing.JTextField txtdatecollected;
    private javax.swing.JTextField txtdonor;
    private javax.swing.JTextField txtqty;
    private javax.swing.JComboBox<String> txtstatus;
    // End of variables declaration//GEN-END:variables
}
