/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package models;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import controller.errorcheck;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import view.Display;
/**
 *
 * @author JC
 */
public class BloodPack extends javax.swing.JFrame implements DBOperations, Display{

    /**
     * Creates new form category
     */
    public BloodPack() {
        initComponents();
        table_update();
        PackType();
    }
    
    String lname;
    String isAdmin;
    String pass;
    int userID;
    
     public BloodPack(String name, String isAdmin, String pass) {
        initComponents();
        this.lname = name;
        this.isAdmin = isAdmin; 
        this.pass = pass;
        table_update();
        getId();
        PackType();
    }

 
    PreparedStatement ptsmnt;
    ResultSet rs;
    
    public void getId(){
        try {
            Connection conl = createConnection();
            ptsmnt = conl.prepareStatement(GET_ID);
            ptsmnt.setString(1, lname);
            ptsmnt.setString(2, pass);
            ResultSet rs = ptsmnt.executeQuery();
            while(rs.next()){
                userID = rs.getInt("id");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this,SYS_ERROR);
            Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void edithistory(String action, int id){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern(DATE_TIME);
        LocalDateTime now = LocalDateTime.now();
        String date = dtf.format(now);
        try {
            Connection conl = createConnection();
            ptsmnt = conl.prepareStatement(INSERT_HISTORY_BLOODPACKS);
            ptsmnt.setInt(1, id);
            ptsmnt.setString(2, action);
            ptsmnt.setString(3, date);
            ptsmnt.setInt(4, userID);
            ptsmnt.executeUpdate();      
            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(this,SYS_ERROR);
                Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    @Override
    public Connection createConnection() throws ClassNotFoundException, SQLException {
        Connection connection = null;
        //enroll the Oracle MySql JDBC Driver
	Class.forName(JDBC_DRIVER_NAME);
	//create or get a Connection
	connection = DriverManager.getConnection(JDBC_URL,DB_USER_NAME, DB_PASSWORD);
	if (connection != null) {
            
	} else {
            
            JOptionPane.showMessageDialog(this, DB_INVALID);
	}
	return connection;
    }
    
    public class PackTypeItem{
        int id;
        String name;
        
        public PackTypeItem(int id, String name){
            this.id = id;
            this.name = name;
        }
        
        public String toString(){
            return name;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtstatus = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtPack = new javax.swing.JComboBox();
        txtdonor = new javax.swing.JTextField();
        txtdatecollected = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtBlood = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(38, 166, 154));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pack Type");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Exit");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Donor");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Blood Pack");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edit History");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Admin");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Blood Pack");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Blood Pack", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setText("Status");

        txtstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Expired" }));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel12.setText("Blood Bag Type");

        jLabel13.setText("Blood Type");

        jLabel15.setText("Donor Name");

        jLabel16.setText("Date Collected");

        txtPack.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "none" }));

        txtdonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdonorActionPerformed(evt);
            }
        });
        txtdonor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdonorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdonorKeyTyped(evt);
            }
        });

        jLabel18.setText("Quantity");

        jLabel19.setForeground(java.awt.Color.red);
        jLabel19.setText("Format: YYYY/MM/DD");

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtBlood.setText("    ");

        jLabel20.setForeground(java.awt.Color.red);
        jLabel20.setText("NOTE: PRESS ENTER AFTER TYPING!!!!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPack, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBlood))
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtdonor, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                .addComponent(txtdatecollected)
                                .addComponent(txtqty)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jLabel19))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtdonor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtPack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(txtdatecollected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtBlood))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel18)
                        .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Blood Pack Type", "Blood Type", "Date Collected", "Donor Name", "Date Registered", "Registered By", "Quantity", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 52, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void PackType(){
        try {
            Connection conl = createConnection();
            ptsmnt = conl.prepareStatement(SELECT_PACKTYPE);
            rs = ptsmnt.executeQuery();
            txtPack.removeAllItems();
            
            while(rs.next()){
                txtPack.addItem(new PackTypeItem(rs.getInt(1), rs.getString(2)));
            }
            
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,SYS_ERROR);
        }
    }
    
    
    public String getName(int id){
        String name = "";
        try {
            Connection conl = createConnection();
            ptsmnt = conl.prepareStatement(GET_NAME);
            ptsmnt.setInt(1, id);
            rs = ptsmnt.executeQuery();
            while(rs.next()){
                name = rs.getString("account_name");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(this,SYS_ERROR);
        }
        return name;
    }
    
    
    public String checkExpiration(String date, int id){
        String newDate = "";
        try {    
            int shelfLife = 0;
            SimpleDateFormat sdf = new SimpleDateFormat(DATE);
            Date currentDate = sdf.parse(date);
            
            try {
                Connection conl = createConnection();
                ptsmnt = conl.prepareStatement(GET_SHELFLIFE);
                ptsmnt.setInt(1, id);
                rs = ptsmnt.executeQuery();
                while(rs.next()){
                    shelfLife = rs.getInt("shelfLife");
                }

                Calendar c = Calendar.getInstance();
                c.setTime(currentDate);
                c.add(Calendar.DATE, shelfLife); 
                newDate = sdf.format(c.getTime());
                
              

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this,SYS_ERROR);
            }
        } catch (ParseException ex) {
            Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,SYS_ERROR);
        }
        return newDate;
    }
      
    public String get_Dname(int id){
        String name = "";
        try {
            Connection conl = createConnection();
            ptsmnt = conl.prepareStatement(SELECT_DONOR);
            ptsmnt.setInt(1, id);
                rs = ptsmnt.executeQuery();
                while(rs.next()){
                    name = rs.getString("donorName");
                }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
        }
        return name;
    }
    
    public boolean checkDonorExist(String name){
        String name2 = "";
        boolean decision = false;
        try {
            Connection conl = createConnection();
            ptsmnt = conl.prepareStatement(CHECK_NAME);
            ptsmnt.setString(1, name);
            rs = ptsmnt.executeQuery();
            while(rs.next()){
                name2 = rs.getString("donorName");
            }
            if(name.equalsIgnoreCase(name2)){
                decision = true;
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
        }
        return decision;
    }
    
    public String getBloodType(int id){
        String bloodType = "";
        try {
            Connection conl = createConnection();
            ptsmnt = conl.prepareStatement(GET_BLOODTYPE);
            ptsmnt.setInt(1, id);
            rs = ptsmnt.executeQuery();
            while(rs.next()){
                bloodType = rs.getString("bloodType");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
        }
        return bloodType;
    }
    
    private void table_update(){
        try {
            int c;
            try {
                Connection conl = createConnection();
                ptsmnt = conl.prepareStatement(UPDATE_TABLE_BLOODPACKS);
                ResultSet rs = ptsmnt.executeQuery();
                ResultSetMetaData rsd = rs.getMetaData();
                c = rsd.getColumnCount();
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern(DATE);
                LocalDateTime now = LocalDateTime.now();
                String presentDate = dtf.format(now);  

                DefaultTableModel d = (DefaultTableModel)jTable1.getModel();
                d.setRowCount(0);
                
                
                while(rs.next()){
                    Vector v2 = new Vector();
                    int id = 0;
                    String status = "";
                    String date = "";
                    String expirationDate = "";
                    c = c - 1;
                    for(int i=1; i<=c; i++){
                       v2.add(rs.getString("id"));
                       id = rs.getInt("packType_id");
                       v2.add(rs.getString("packType"));
                       v2.add(rs.getString("bloodType"));
                       date = rs.getString("date_collected");
                       v2.add(date);
                       v2.add(get_Dname(rs.getInt("donor_id")));
                       v2.add(rs.getString("date_registered"));
                       v2.add(getName(rs.getInt("account_id")));
                       v2.add(rs.getString("quantity"));
                       status = rs.getString("status");
                       expirationDate = checkExpiration(date, id);

                       if(presentDate.equals(expirationDate)){
                            status = "Expired";
                        } 
                        v2.add(status);
                    }
                    
                    d.addRow(v2);
                }               
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this,SYS_ERROR);
            }
        } catch (SQLException ex) {
            Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(this,SYS_ERROR);
        }
    }
    
    
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         jButton1.setEnabled(false);
         DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
         int selectIndex = jTable1.getSelectedRow();
         txtPack.setSelectedIndex(-1);
         txtBlood.setText(d1.getValueAt(selectIndex, 2).toString());
         txtdatecollected.setText(d1.getValueAt(selectIndex, 3).toString());
         txtdonor.setText(d1.getValueAt(selectIndex, 4).toString());
         txtqty.setText(d1.getValueAt(selectIndex, 7).toString());
         txtstatus.setSelectedItem(d1.getValueAt(selectIndex, 8).toString());   
         String status = txtstatus.getSelectedItem().toString();   
         if(status.equals("Expired")){
           jButton2.setEnabled(false);
         } else {
            jButton2.setEnabled(true);
         }
          
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.hide();
        new PackType(lname,isAdmin,pass).setVisible(true);
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.hide();
        new BloodType(lname,isAdmin,pass).setVisible(true);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1. getSelectedRow();

        int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());

        int dialogResult = JOptionPane.showConfirmDialog(this, DELETE_RECORD, "Warning",JOptionPane.YES_NO_OPTION);

        if(dialogResult == JOptionPane.YES_OPTION){

            try {
                Connection conl = createConnection();
                ptsmnt = conl.prepareStatement(DELETE_BLOODPACK);
                ptsmnt.setInt(1, id);
                ptsmnt.executeUpdate();
                JOptionPane.showMessageDialog(this, RECORD_DELETED);
                table_update();
                reloadAll();
                txtdonor.requestFocus();
                edithistory(BP_ID_DELETED, id);
                jButton1.setEnabled(true);

            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(this,SYS_ERROR);
                Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    public int get_DID(String name){
        int id = 0;
        try {
            Connection conl = createConnection();
            ptsmnt = conl.prepareStatement(GET_DID);
            ptsmnt.setString(1, name);
            rs = ptsmnt.executeQuery();
            while(rs.next()){
                id = rs.getInt("id");
            }
         
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        errorcheck err = new errorcheck();// Calls the error and restriction methods 
        
        DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1. getSelectedRow();
        int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());        
        if(txtPack.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, COMBO_EMP);
        } else {
            String donor = txtdonor.getText();
            if(checkDonorExist(donor) == false){
                JOptionPane.showMessageDialog(this, "Donor's name is not on the Database!!!");
                JOptionPane.showMessageDialog(this, "Register Donor First!!!");
                txtdonor.requestFocus();
            } else if(err.isEmpty(donor)){
                JOptionPane.showMessageDialog(this, NOT_EMPTY);
                txtdonor.requestFocus();
            } else {
               String datec = txtdatecollected.getText();
                PackTypeItem pitem = (PackTypeItem)txtPack.getSelectedItem();
                String qty = txtqty.getText();
                String status = txtstatus.getSelectedItem().toString();
                int donor_id = get_DID(donor);
                txtBlood.setText(getBloodType(donor_id));
                String bloodType = txtBlood.getText();
                try {
                    Connection conl = createConnection();
                    ptsmnt = conl.prepareStatement(UPDATE_BLOODPACK);
                    ptsmnt.setInt(1, donor_id);
                    //If input String value is empty
                    if(err.isEmpty(donor) == true){
                        JOptionPane.showMessageDialog(this, NOT_EMPTY);
                        txtdonor.requestFocus();
                    }
                    //If input contains illegal characters that are not good for databases
                    else if(err.isContainIllegalChar(donor) == true){
                        JOptionPane.showMessageDialog(this, NO_ILLEGAL_CHAR);
                        txtdonor.requestFocus();
                    }
                    //If input is number only
                    else if(err.numberOrNot(donor)== true){
                       JOptionPane.showMessageDialog(this, NAME_NUM);
                       txtdonor.requestFocus();
                    }

                    //Proceeds to data collection checking
                    else{
                         ptsmnt.setString(2, datec);
                        //If input String value is empty
                        if(err.isEmpty(datec) == true){
                            JOptionPane.showMessageDialog(this, DATE_EMPTY);
                        }
                        //If input value does not follow the format that was specified
                        else if(err.isValidFormat(datec) == true){
                            JOptionPane.showMessageDialog(this, DATE_FORMAT);
                        }

                        //Proceeds to data collection checking
                        else{
                            ptsmnt.setInt(3, pitem.id);
                            ptsmnt.setString(4, bloodType);

                            ptsmnt.setString(5, qty);
                            //If input String value is empty
                            if(err.isEmpty(qty) == true){
                                JOptionPane.showMessageDialog(this, NOT_EMPTY);
                                txtqty.requestFocus();
                            }
                            //If input String value contains letters
                            else if(err.isLetter(qty) == true){
                                JOptionPane.showMessageDialog(this, QTY_NUM);
                                txtqty.requestFocus();
                            }

                            //Proceeds to data collection checking
                            else{
                                ptsmnt.setString(6, status);
                                ptsmnt.setInt(7, id);
                                ptsmnt.executeUpdate();
                                JOptionPane.showMessageDialog(this, BP_UPDATED);
                                table_update();
                                txtdonor.setText("");
                                txtdatecollected.setText("");               
                                txtqty.setText("");   
                                txtdonor.requestFocus();
                                edithistory(BP_ID_UPDATED,id); 
                                jButton1.setEnabled(true);
                            }


                        }

                    }


                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this,SYS_ERROR);
                } 
            }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        errorcheck err = new errorcheck();// Calls the error and restriction methods 
        
        String donor = txtdonor.getText();
        if(checkDonorExist(donor) == false){
                JOptionPane.showMessageDialog(this, "Donor's name is not on the Database!!!");
                JOptionPane.showMessageDialog(this, "Register Donor First!!!");
                txtdonor.requestFocus();
            } else if(err.isEmpty(donor)){
                JOptionPane.showMessageDialog(this, NOT_EMPTY);
                txtdonor.requestFocus();
            } else {
            String datec = txtdatecollected.getText();
            if(txtPack.getSelectedIndex() == -1 ){
                JOptionPane.showMessageDialog(this, COMBO_EMP);
            } else {
                PackTypeItem pitem = (PackTypeItem)txtPack.getSelectedItem();
                String qty = txtqty.getText();
                String status = txtstatus.getSelectedItem().toString();
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern(DATE);
                LocalDateTime now = LocalDateTime.now();
                String dater = dtf.format(now);
                int donor_id = get_DID(donor);
                String bloodType = txtBlood.getText();


                int generatedID = 0;
                try {
                    Connection conl = createConnection();
                    ptsmnt = conl.prepareStatement(INSERT_BLOODPACK,Statement.RETURN_GENERATED_KEYS);
                    ptsmnt.setInt(1, pitem.id);
                    ptsmnt.setString(2, bloodType);
                    ptsmnt.setString(3, datec);
                    //If input String value is empty
                    if(err.isEmpty(datec) == true){
                        JOptionPane.showMessageDialog(this, DATE_EMPTY);
                        txtdatecollected.requestFocus();
                    }
                    //If input value does not follow the format that was specified
                    else if(err.isValidFormat(datec) == true){
                        JOptionPane.showMessageDialog(this, DATE_FORMAT);
                        txtdatecollected.requestFocus();
                    }

                    //Proceed to checking donorname for any irregularities
                    else{
                        ptsmnt.setInt(4, donor_id);

                        //If input String value is empty
                        if(err.isEmpty(donor) == true){
                            JOptionPane.showMessageDialog(this, NOT_EMPTY);
                            txtdonor.requestFocus();
                        }
                        //If input contains illegal characters that are not good for databases
                        else if(err.isContainIllegalChar(donor) == true){
                            JOptionPane.showMessageDialog(this, NO_ILLEGAL_CHAR);
                            txtdonor.requestFocus();
                        }
                        //If input is number only
                        else if(err.numberOrNot(donor)== true){
                           JOptionPane.showMessageDialog(this, NAME_NUM);
                           txtdonor.requestFocus();
                        }

                        //Proceed to data insertion
                        else{
                            ptsmnt.setString(5, dater);     
                            ptsmnt.setInt(6, userID);
                            ptsmnt.setString(7, qty);
                            //If input String value is empty
                            if(err.isEmpty(qty) == true){
                                JOptionPane.showMessageDialog(this, NOT_EMPTY);
                                txtqty.requestFocus();
                            }
                            //If input String value contains letters
                            else if(err.isLetter(qty) == true){
                                JOptionPane.showMessageDialog(this, QTY_NUM);
                                txtqty.requestFocus();
                            }
                            else{
                                ptsmnt.setString(8, status);
                                ptsmnt.executeUpdate();
                                ResultSet generatedKeyResult = ptsmnt.getGeneratedKeys();
                                if(generatedKeyResult.next()){
                                    generatedID = generatedKeyResult.getInt(1);
                                }
                                JOptionPane.showMessageDialog(this, BP_ADD_ID + generatedID );
                                table_update();
                                txtdonor.setText("");
                                txtdatecollected.setText("");  
                                txtqty.setText(""); 
                                txtdonor.requestFocus();
                                edithistory(BP_ADD_ID , generatedID ); 

                            }


                        }


                    }

                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(BloodPack.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this,SYS_ERROR);
                }

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.hide();
        new EditHistory(lname,isAdmin,pass).setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
       if(isAdmin.equals("Yes")){
            this.hide();
            new Accounts(lname,isAdmin,pass).setVisible(true);
       }  else {
           JOptionPane.showMessageDialog(this, ADMIN_ONLY);
           int dialogResult = JOptionPane.showConfirmDialog(this, LOGIN_AS_ADMIN, "Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                login l = new  login();
                this.hide();
                l.setVisible(true);
            }
       }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void txtdonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdonorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdonorActionPerformed

    public void reloadAll(){
        txtdonor.setText("");
        txtdatecollected.setText("");  
        txtqty.setText(""); 
        txtdonor.requestFocus();
        txtPack.setSelectedIndex(-1);
        txtBlood.setText("");
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jButton1.setEnabled(true);
        reloadAll();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtdonorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdonorKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String name = txtdonor.getText();
            txtBlood.setText(getBloodType(get_DID(name)));
        }
    }//GEN-LAST:event_txtdonorKeyPressed

    private void txtdonorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdonorKeyTyped
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtdonorKeyTyped

    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BloodPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BloodPack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel txtBlood;
    private javax.swing.JComboBox txtPack;
    private javax.swing.JTextField txtdatecollected;
    private javax.swing.JTextField txtdonor;
    private javax.swing.JTextField txtqty;
    private javax.swing.JComboBox<String> txtstatus;
    // End of variables declaration//GEN-END:variables
}
