/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;


//import com.sun.istack.internal.logging.Logger;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Accounts;
import models.BloodPack;
import models.Donor;
import models.EditHistory;
import models.PackType;
import models.ViewAll;
//import sun.util.logging.PlatformLogger;
import view.Display;
/**
 *
 * @author JC
 */
public class main extends javax.swing.JFrame implements Display {

    /**
     * Creates new form category
     */
    public main() {
        initComponents();
      
    }

    String lname;
    String isAdmin;
    String pass;
    int bloodBank_id;
    int userID;
    
     public main(String name, String isAdmin, String pass, int bloodBank_id, int userID) {
        initComponents();
        this.bloodBank_id = bloodBank_id;
        this.lname = name;
        this.isAdmin = isAdmin;
        this.pass = pass;
        usertxt.setText(lname);  
       
        this.userID = userID;
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        usertxt = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        header_panel = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        exit_icon = new javax.swing.JLabel();
        minimize_icon = new javax.swing.JLabel();
        minimize_maximize_icon = new javax.swing.JToggleButton();
        sidePanelHide = new javax.swing.JToggleButton();
        leftSidePanel = new javax.swing.JPanel();
        exitLink = new javax.swing.JLabel();
        donorLink = new javax.swing.JLabel();
        bloodPackLink = new javax.swing.JLabel();
        editHistoryLink = new javax.swing.JLabel();
        adminLink = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        viewAllBloodBankLink = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("*picture can be changed depending on what hospital the system is installed on");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(360, 220, 820, 60);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Welcome");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel7);
        jLabel7.setBounds(490, 70, 260, 50);

        usertxt.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        usertxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usertxt.setText("username");
        usertxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(usertxt);
        usertxt.setBounds(390, 150, 480, 41);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/z-res-images/stlukes-01.jpeg"))); // NOI18N
        jPanel3.add(jLabel18);
        jLabel18.setBounds(-110, -30, 1250, 690);

        header_panel.setBackground(new java.awt.Color(38, 166, 154));

        header.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setText("Blood Bank Management System");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/z-res-images/icons8_syringe_with_a_drop_of_blood_60px.png"))); // NOI18N

        exit_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_iconMouseClicked(evt);
            }
        });

        minimize_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_iconMouseClicked(evt);
            }
        });

        minimize_maximize_icon.setBorder(null);
        minimize_maximize_icon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimize_maximize_iconActionPerformed(evt);
            }
        });

        sidePanelHide.setText("Hide");
        sidePanelHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidePanelHideActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidePanelHide, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(header_panelLayout.createSequentialGroup()
                        .addGap(793, 793, 793)
                        .addComponent(minimize_icon)
                        .addGap(7, 7, 7)
                        .addComponent(minimize_maximize_icon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit_icon))
                    .addGroup(header_panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit_icon)
                    .addComponent(minimize_icon)
                    .addComponent(minimize_maximize_icon))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_panelLayout.createSequentialGroup()
                        .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(header))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_panelLayout.createSequentialGroup()
                        .addComponent(sidePanelHide, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        leftSidePanel.setBackground(new java.awt.Color(38, 166, 154));

        exitLink.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exitLink.setForeground(new java.awt.Color(255, 255, 255));
        exitLink.setText("Exit");
        exitLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLinkMouseExited(evt);
            }
        });

        donorLink.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        donorLink.setForeground(new java.awt.Color(255, 255, 255));
        donorLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/z-res-images/icons8_people_30px_1.png"))); // NOI18N
        donorLink.setText("Donor");
        donorLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donorLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                donorLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                donorLinkMouseExited(evt);
            }
        });

        bloodPackLink.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        bloodPackLink.setForeground(new java.awt.Color(255, 255, 255));
        bloodPackLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/z-res-images/icons8_rh+_30px.png"))); // NOI18N
        bloodPackLink.setText("Blood-Pack");
        bloodPackLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bloodPackLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bloodPackLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bloodPackLinkMouseExited(evt);
            }
        });

        editHistoryLink.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        editHistoryLink.setForeground(new java.awt.Color(255, 255, 255));
        editHistoryLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editHistoryLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/z-res-images/icons8_edit_property_30px.png"))); // NOI18N
        editHistoryLink.setText("Activity Logs");
        editHistoryLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editHistoryLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editHistoryLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editHistoryLinkMouseExited(evt);
            }
        });

        adminLink.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        adminLink.setForeground(new java.awt.Color(255, 255, 255));
        adminLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/z-res-images/icons8_admin_settings_male_30px.png"))); // NOI18N
        adminLink.setText("Admin");
        adminLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminLinkMouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/z-res-images/icons8_exit_30px.png"))); // NOI18N

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/z-res-images/icons8_welfare_70px.png"))); // NOI18N

        viewAllBloodBankLink.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        viewAllBloodBankLink.setForeground(new java.awt.Color(255, 255, 255));
        viewAllBloodBankLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/z-res-images/icons8_view_30px.png"))); // NOI18N
        viewAllBloodBankLink.setText("View Blood Banks");
        viewAllBloodBankLink.setFocusable(false);
        viewAllBloodBankLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAllBloodBankLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewAllBloodBankLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewAllBloodBankLinkMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/z-res-images/icons8_product_30px_1.png"))); // NOI18N
        jLabel1.setText("Pack-Type");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout leftSidePanelLayout = new javax.swing.GroupLayout(leftSidePanel);
        leftSidePanel.setLayout(leftSidePanelLayout);
        leftSidePanelLayout.setHorizontalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(donorLink)
                    .addComponent(editHistoryLink)
                    .addComponent(adminLink)
                    .addComponent(viewAllBloodBankLink, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodPackLink, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitLink))
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)))
        );
        leftSidePanelLayout.setVerticalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(donorLink)
                .addGap(36, 36, 36)
                .addComponent(bloodPackLink)
                .addGap(39, 39, 39)
                .addComponent(editHistoryLink)
                .addGap(37, 37, 37)
                .addComponent(adminLink)
                .addGap(34, 34, 34)
                .addComponent(viewAllBloodBankLink, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitLink))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(leftSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(header_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(leftSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("JFrame");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLinkMouseClicked
        // TODO add your handling code here:
       if(isAdmin.equals("Admin")){
            this.dispose();
            new Accounts(lname,isAdmin,pass,bloodBank_id,userID).setVisible(true);
       }  else {
           JOptionPane.showMessageDialog(this, ADMIN_ONLY);
           int dialogResult = JOptionPane.showConfirmDialog(null, LOGIN_AS_ADMIN, "Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                login l = new  login();
                this.dispose();
                l.setVisible(true);
            }
       }       
    }//GEN-LAST:event_adminLinkMouseClicked

    private void exitLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLinkMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitLinkMouseClicked

    private void editHistoryLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editHistoryLinkMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new EditHistory(lname,isAdmin,pass,bloodBank_id,userID).setVisible(true);
    }//GEN-LAST:event_editHistoryLinkMouseClicked

    private void bloodPackLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloodPackLinkMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new BloodPack(lname,isAdmin,pass,bloodBank_id,userID).setVisible(true);
    }//GEN-LAST:event_bloodPackLinkMouseClicked

    private void donorLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donorLinkMouseClicked
        // TODO add your handling code here:
       this.dispose();
       new Donor(lname,isAdmin,pass,bloodBank_id,userID).setVisible(true);

    }//GEN-LAST:event_donorLinkMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new PackType(lname,isAdmin,pass,bloodBank_id,userID).setVisible(true);

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel1.setForeground(Color.cyan);
       
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setForeground(Color.white);
    }//GEN-LAST:event_jLabel1MouseExited

    private void donorLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donorLinkMouseEntered
        // TODO add your handling code here:
         donorLink.setForeground(Color.cyan);
    }//GEN-LAST:event_donorLinkMouseEntered

    private void donorLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donorLinkMouseExited
        // TODO add your handling code here:
        donorLink.setForeground(Color.white);
    }//GEN-LAST:event_donorLinkMouseExited

    private void bloodPackLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloodPackLinkMouseEntered
        // TODO add your handling code here:
        bloodPackLink.setForeground(Color.cyan);
    }//GEN-LAST:event_bloodPackLinkMouseEntered

    private void bloodPackLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloodPackLinkMouseExited
        // TODO add your handling code here:
        bloodPackLink.setForeground(Color.white);
    }//GEN-LAST:event_bloodPackLinkMouseExited

    private void editHistoryLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editHistoryLinkMouseEntered
        // TODO add your handling code here:
        editHistoryLink.setForeground(Color.cyan);
    }//GEN-LAST:event_editHistoryLinkMouseEntered

    private void editHistoryLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editHistoryLinkMouseExited
        // TODO add your handling code here:
        editHistoryLink.setForeground(Color.white);
    }//GEN-LAST:event_editHistoryLinkMouseExited

    private void exitLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLinkMouseEntered
        // TODO add your handling code here:
        exitLink.setForeground(Color.cyan);
    }//GEN-LAST:event_exitLinkMouseEntered

    private void exitLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLinkMouseExited
        // TODO add your handling code here:
        exitLink.setForeground(Color.white);
    }//GEN-LAST:event_exitLinkMouseExited

    private void adminLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLinkMouseEntered
        // TODO add your handling code here:
        adminLink.setForeground(Color.cyan);
    }//GEN-LAST:event_adminLinkMouseEntered

    private void adminLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLinkMouseExited
        // TODO add your handling code here:
        adminLink.setForeground(Color.white);
    }//GEN-LAST:event_adminLinkMouseExited

    private void viewAllBloodBankLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllBloodBankLinkMouseClicked
        // TODO add your handling code here:
        this.hide();
        new ViewAll(lname, isAdmin, pass, bloodBank_id, userID).setVisible(true);
    }//GEN-LAST:event_viewAllBloodBankLinkMouseClicked

    private void viewAllBloodBankLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllBloodBankLinkMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_viewAllBloodBankLinkMouseEntered

    private void viewAllBloodBankLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllBloodBankLinkMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_viewAllBloodBankLinkMouseExited


    private void sidePanelHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidePanelHideActionPerformed
    
         if(sidePanelHide.isSelected()){
             leftSidePanel.setVisible(false);
             sidePanelHide.setText("Show");
         }
         else{
             leftSidePanel.setVisible(true);
             sidePanelHide.setText("Hide");
         }
    }//GEN-LAST:event_sidePanelHideActionPerformed

    private void exit_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_iconMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exit_iconMouseClicked

    private void minimize_maximize_iconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimize_maximize_iconActionPerformed
         //If selected them frame will be maximied
        if(minimize_maximize_icon.isSelected()){
          setExtendedState(JFrame.MAXIMIZED_BOTH); // To maximize a frame
         }
        
        //If selected frame will be normalize
         else{
             setState(JFrame.NORMAL); // To normalized a frame
             
         }
    }//GEN-LAST:event_minimize_maximize_iconActionPerformed

    private void minimize_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_iconMouseClicked
       setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize_iconMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminLink;
    private javax.swing.JLabel bloodPackLink;
    private javax.swing.JLabel donorLink;
    private javax.swing.JLabel editHistoryLink;
    private javax.swing.JLabel exitLink;
    private javax.swing.JLabel exit_icon;
    private javax.swing.JLabel header;
    private javax.swing.JPanel header_panel;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel leftSidePanel;
    private javax.swing.JLabel minimize_icon;
    private javax.swing.JToggleButton minimize_maximize_icon;
    private javax.swing.JToggleButton sidePanelHide;
    private javax.swing.JLabel usertxt;
    private javax.swing.JLabel viewAllBloodBankLink;
    // End of variables declaration//GEN-END:variables

}
