/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import model.KeyGenerator;
import model.AboutUs;

/**
 *
 * @author Altheo
 */
public class ControlPanelDev extends javax.swing.JFrame {

    /**
     * Creates new form ControlPanelDev
     */
    public ControlPanelDev() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KeyGeneratorLink1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        KeyGeneratorLink3 = new javax.swing.JLabel();
        KeyGeneratorLink = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        topHeader = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        KeyGeneratorLink1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KeyGeneratorLink1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KeyGeneratorLink1.setText("KEY GENERATOR");
        KeyGeneratorLink1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        KeyGeneratorLink1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        KeyGeneratorLink1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KeyGeneratorLink1MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("ControlPanelMenu"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        KeyGeneratorLink3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        KeyGeneratorLink3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KeyGeneratorLink3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/z-res-images/icons8_info_100px_3.png"))); // NOI18N
        KeyGeneratorLink3.setText("ABOUT US             ");
        KeyGeneratorLink3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        KeyGeneratorLink3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KeyGeneratorLink3MouseClicked(evt);
            }
        });

        KeyGeneratorLink.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        KeyGeneratorLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KeyGeneratorLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/z-res-images/icons8_grand_master_key_100px_1.png"))); // NOI18N
        KeyGeneratorLink.setText("KEY-GENERATOR");
        KeyGeneratorLink.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        KeyGeneratorLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KeyGeneratorLinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(KeyGeneratorLink3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(KeyGeneratorLink, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(KeyGeneratorLink, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KeyGeneratorLink3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(38, 166, 154));

        topHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        topHeader.setForeground(new java.awt.Color(255, 255, 255));
        topHeader.setText("DEVELOPER CONTROL PANEL");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("yormesoftware™");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/z-res-images/icons8_crown_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(topHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(topHeader)))
                .addGap(35, 35, 35))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KeyGeneratorLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeyGeneratorLinkMouseClicked
        this.hide();
        new KeyGenerator().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KeyGeneratorLinkMouseClicked

    private void KeyGeneratorLink1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeyGeneratorLink1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_KeyGeneratorLink1MouseClicked

    private void KeyGeneratorLink3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeyGeneratorLink3MouseClicked
        // TODO add your handling code here:
         this.hide();
        new AboutUs().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KeyGeneratorLink3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlPanelDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlPanelDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlPanelDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlPanelDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlPanelDev().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KeyGeneratorLink;
    private javax.swing.JLabel KeyGeneratorLink1;
    private javax.swing.JLabel KeyGeneratorLink3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel topHeader;
    // End of variables declaration//GEN-END:variables
}
